### ISSUE TITLE
Issue trying to upload some updated records

### ISSUE THREAD

**Issue by wpiedrahita** [forcedotcom/CustomMetadataLoader#10]
Haga clic para abrir la barra lateral 	El contenido empieza aquí
Web service callout failed: WebService returned a SOAP Fault: Unknown SObject Namespace for Metadata Error Id: 394018059-2725 (-1586907319) faultcode=soapenv:Server faultactor=
El error está en la expresión '{!upsertCustomMetadata}' del componente <apex:commandButton> en page custommetadatarecorduploader: Class.MetadataService.MetadataPort.upsertMetadata: line 9261, column 1
Class.MetadataUtil.upsertMetadataAndValidate: line 131, column 1
Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 97, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 127, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by ddeveaux** [comment]
We've been getting this since before Spring '17. Got exact same error today when trying to update a record using Loader. Tried reinstalling .zip no change

**Comment by amarkulkarni-RC** [comment]
I'm also getting the same issue today. Is there a solution/patch for this?

**Comment by sricharananand** [comment]
We have received a case for it, investigating the issue.

**Comment by sricharananand** [comment]
This issue should be fixed in latest patch that was rolled out to all instances. Closing the issue.
