### ISSUE TITLE
Error Deploying CustomMetadataLoader Into Production

### ISSUE THREAD

**Issue by ddeveaux** [forcedotcom/CustomMetadataLoader#12]
Got below today.

Deployment CompleteTest failure, method: CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName -- System.NullPointerException: Attempt to de-reference a null object stack Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
Class.CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName: line 54, column 1

Test failure, method: CustomMetadataUploadControllerTest.testCreateCustomMetadata -- System.NullPointerException: Attempt to de-reference a null object stack Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
Class.CustomMetadataUploadControllerTest.testCreateCustomMetadata: line 44, column 1

**Comment by tehn-r** [comment]
Also, Unit Tests should be data independent, so we can delete CountryMapping__mdt and no tests failed

**Comment by disasterlooms** [comment]
I got the same error as ddeveaux. Should I just delete Country_Mapping_mdt ?

**Comment by millerterry** [comment]
I'm in the same boat with @ddeveaux & @disasterlooms.  I get the following errors from WorkBench when trying to deploy the custom_md_loader.zip.  Any fixes available?  I was able to deploy to my sandbox but not Production.

failures (3)

CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName
id: 01p44000002XfohAAC
message: System.NullPointerException: Attempt to de-reference a null object
methodName: testCreateCustomMetadataWithDevName
name: CustomMetadataUploadControllerTest
namespace:
packageName: CustomMetadataUploadControllerTest
stackTrace: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1 Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1 Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1 Class.CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName: line 54, column 1
time: 133
type: Class

CustomMetadataUploadControllerTest.testCreateCustomMetadata
id: 01p44000002XfohAAC
message: System.NullPointerException: Attempt to de-reference a null object
methodName: testCreateCustomMetadata
name: CustomMetadataUploadControllerTest
namespace:
packageName: CustomMetadataUploadControllerTest
stackTrace: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1 Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1 Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1 Class.CustomMetadataUploadControllerTest.testCreateCustomMetadata: line 44, column 1
time: 134
type: Class

TestOppSplitTrigger.myUnitTest
id: 01pE0000002K3CjIAK
message: System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Product_Type__c]: [Product_Type__c]
methodName: myUnitTest
name: TestOppSplitTrigger
namespace:
packageName: TestOppSplitTrigger
stackTrace: Class.TestOppSplitTrigger.myUnitTest: line 43, column 1
time: 1479
type: Class
