### ISSUE TITLE
Cannot get the sample to work

### ISSUE THREAD

**Issue by irinaclington** [forcedotcom/CustomMetadataLoader#14]
When I try to load the sample the following error occurs
Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
Could someone please help me out?
We want to move some of our custom objects to custom metadata but without a good way to migrate them it will be very difficult.

**Comment by irinaclington** [comment]
It works with revert-11-master

**Comment by RahimRahimov** [comment]
@irinaclington Could you please explain how did you fix this problem? I have the same issue. What is revert-11-master?

**Comment by irinaclington** [comment]
revert-11-master Updated 2 months ago by sricharananand
There are two branches, instead of using master I used the one above instead. I have only used this in a sandbox and not in production since I don't find this stable enough to go to prod.
