### ISSUE TITLE
Error Deploying CustomMetadataLoader Into Production

### ISSUE THREAD

**Issue by disasterlooms** [forcedotcom/CustomMetadataLoader#15]
System.NullPointerException: Attempt to de-reference a null object 
Stack Trace: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1 Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1 Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1 Class.CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName: line 54, column 1

**Comment by sricharananand** [comment]
Issue should be resolved now via commit on Aug 9, 2017 - closing this issue.
