### ISSUE TITLE
CSV file upload in visualforce page 

### ISSUE THREAD

**Issue by harshabushan** [forcedotcom/CustomMetadataLoader#16]
Hi Team,

Please could help me out for CSV File upload 

I have Writing code it's working fine.
but i have want to use custom setting get the values in map

if you go through code 
 String Oppid = inputvalues[1].trim(); // this is hard code values i am pass

I need to pass csv file sheet values in custom setting and custom setting values in code 
 
/********************************************************************************************************
// Name             : BulkFeasibilityFileUploader.cls
// Description      : Class to Read CSV File & insert Data On Request, Task & Response.
// Created By       : Harsha Naik, TCS
// Created Date     : 04 May 2017

public with sharing class BundleFeasibilityController {

        public string csvFileName{get;set;} // To Capture uploaded file
        public transient Blob contentFile{get;set;} // To Capture body of the file
        transient public String[] filelines = new String[]{};// To Capture he no. of lines in the file
        public Boolean successFlag{get;set;} //check it boolean flag
        public string Labelvalue{get;set;} // to check the customlabel values
        public String fileExtention = '.csv';  // To check the correct file extention
       
        

        public list<string>opptyIdList =new list<string>(); // to capture column values in list 
        public list<string>prodtypeList =new list<string>();// to capture column values in list
        public list<String>cityList = new List<String>(); // to capture column values in list
        public list<string>networkSolCktList =new list<string>(); // to capture column values in list
        public list<string>CustomerSiteList =new list<string>(); // to capture column values in list
        public List<Database.SaveResult> saveResult = new List<Database.SaveResult>(); // To capture Insert  Result for Request/Task/Respone.

        public Map<String,id> opptyIdProdTypeMap =new Map<String,id>(); //to capture column values in Map
        public Map<String,id> cityMap =new Map<String,id>(); //to capture column values in Map
        public Map<String,id> networkSolCktMap =new Map<String,id>(); //to capture column values in Map
        public Map<String,id> CustomerSiteMap =new Map<String,id>();  //to capture column values in Map 
        public Map<string,id> Opportunitymap = New Map<string,id>();  //to capture column values in Map

        
       public List<Case> successcaseList {get;set;} // Query the list case object
       public List<Case> caseList = new List<Case>(); // case object 
       public List<Feasibility_Task__c> FeasibilityTasklist1 =new List<Feasibility_Task__c>(); // Feasibility_Task__c object
       public list<Feasibility_Response_A__c> FeasibilityResponselist =new list<Feasibility_Response_A__c>(); // Feasibility_Response_A__c object
        
        public List<Id> fReqIdList = new List<Id>(); //To capture the Case Ids of  successfully inserted
        public list<id> fReqIdListerror =new list<id>(); //To capture the ID of failures 
        public list<id> FeasibilityTaskId =new list<id>();  //To capture the  Feasibility_Task__c Ids of successfully inserted
        public list<id> FeasibilityResponseId =new list<id>();//To capture the Feasibility_Response_A__c Ids of successfully inserted
        public list<id> caseid =new list<id>();

        /* siteloaction list */
        //public list<string> newjoin =new list<string>(); // to capture
        public List<Site_Location_ID__c> siteObjListresult = new List<Site_Location_ID__c>(); //  Query the list Site_Location_ID__c  object 
        public List<Site_Location_ID__c> siteObjList = new List<Site_Location_ID__c>(); // to capture list values in Site_Location_ID__c

    
    public BundleFeasibilityController(){
     //successFlag=true;
    
    }
    Public BundleFeasibilityController (ApexPages.StandardController controller) {
         //this.successcaseList= new List<Case>();
        successFlag = false;
    }
 
    public Pagereference ReadFile() {  
    Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Default Feasibility Request').getRecordTypeId();   
      /*
       if(test.isRunningTest())
       {
           csvFileName='testharshanaiktest.csv';
           string str = 'Sr.no,Opportunity ID,Product Name,Ckt ServiceID ,Customer Site ID ,Network Solution Circuit ID,Continent(A-End),Country (A-End) ,State (A-End),City (A End),Pin/Zip (A-End),ADDRESS LINE1(A-End),ADDRESS LINE2(A-End) ,ADDRESS LINE3 (A-End),Floor(A-End) ,Room(A-End) ,Rack(A-End) ,Continent(B-End) ,Country (B-End),State (B-End) ,City (B End) ,Pin/Zip (B-End) ,ADDRESS LINE1(B-End) ,ADDRESS LINE2(B-End) ,ADDRESS LINE3(B-End) ,Floor(B-End) ,Rack(B-End) ,Room(B-End) \r\n ';
           str = str +' 1,1758856,Hub - Global Dedicated Ethernet,12222,2222,,Asia,India,Maharashtra,Pune,400079,addresss1,Address1,addresss1,4th ,301,2221,Asia,India,Maharashtra,Pune,400079,addresss1,Address1,addresss1,4th,301,2221'; 
           contentfile = blob.valueof(str);
           
       }
      */
        System.debug('pkp csvFileName :'+ csvFileName);
       if(csvFileName !=null){
           if(csvFileName.subString(csvFileName.length() - 4, csvFileName.length()).equals(fileExtention)){
           
                              
               // csvFileName = blobToString( contentFile,'ISO-8859-1');
                csvFileName=contentFile.toString();
                    system.debug('csvFileName.length()' +csvFileName.length());
                    if(csvFileName.length() >30000) {
                        ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'File size is too large.Please reduce number of records in the file and try again');
                        ApexPages.addMessage(errormsg);
                        return null;
                    } 
                   
                 system.debug('pkp csvFileName :::: '+csvFileName)  ; 
                 filelines = csvFileName.split('\n');
                    system.debug('filelines' + filelines.size());
                    if(filelines.size() > 25) {
                    ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'Upto 25 activities are loaded at a time');
                    ApexPages.addMessage(errormsg);
                    return null;
                    }
                   system.debug('pkp1 filelines :::: '+filelines)  ;
                   //.replaceAll(',(?=[^"]*"[^"]*(?:"[^"]*"[^"]*)*$)','&COMMA')
                   
               system.debug('pkp2 filelines :::: '+filelines.size() + filelines )  ;
               //integer fileSize = filelines.size();
               //if(Test.isrunningTest()){fileSize = fileSize +1;}
                    For (Integer i=1;i<filelines.size();i++)
                    {
                        System.debug('pkp filelines :::'+filelines);
                        String[] inputvalues = new String[]{};
                        inputvalues = filelines[i].split(',');
                        String Oppid = inputvalues[1].trim();
                        system.debug('Oppid' + oppid);
                        String Prodtyp = inputvalues[2].trim();
                        system.debug('Prodtyp ' + Prodtyp );
                        String CustomerSiteID = inputvalues[4].trim();
                        String netSolCktId = inputvalues[5].trim();
                        String city=inputvalues[9].trim();
                        opptyIdList.add(Oppid);
                        system.debug('opptyIdList' + opptyIdList);
                        prodtypeList.add(Prodtyp);
                        system.debug('prodtypeList' + prodtypeList);  
                        CustomerSiteList.add(CustomerSiteID);
                        system.debug('CustomerSiteList'  + CustomerSiteList); 
                        networkSolCktList.add(netSolCktId);
                        system.debug('networkSolCktList'  + networkSolCktList);               
                        cityList.add(city); 
                        system.debug('cityList' + cityList);
                        //StateList.add(State);
                       // opptyIdCustSiteIdMap.put(Oppid,CustomerSiteID);
                        
                        

                    }  
                    if(opptyIdList!=null && !opptyIdList.isEmpty() && prodtypeList!=null && !prodtypeList.isEmpty()) {

                                for(Products_Services__c pr:[Select Id,Opportunity_SFDC_ID__c,Name,Product_Type__c From Products_Services__c where Opportunity_SFDC_ID__c IN:opptyIdList AND Product_Type__c IN:prodtypeList]){       
                                opptyIdProdTypeMap.put(pr.Opportunity_SFDC_ID__c+'_'+pr.Product_Type__c,pr.Id);      
                                System.debug('opptyIdProdTypeMap::'  + opptyIdProdTypeMap);
                            }

                    }
                    if(opptyIdList!=null && !opptyIdList.isEmpty()){
                            
                        for(Opportunity opp:[Select Id,AccountId,CurrencyISOCODE,Name,Opportunity_ID__c, is_partner_Order__c,Account.Profile__c from Opportunity where Opportunity_ID__c IN:opptyIdList]){
                                           Opportunitymap.put(opp.Opportunity_ID__c,opp.AccountId);
                                           System.debug('Opportunitymap::'+ Opportunitymap);
                                           
                                      }
                                
                    }
                    if(cityList!=null && !cityList.isEmpty()){
                        
                            for(CityStateCountryMD__c city:[Select Id,Name,State__c from CityStateCountryMD__c where Name in:cityList]){ 
                               
                                        cityMap.put(city.Name,city.Id);   
                                        System.debug('cityMap1' + cityMap); 
                                                   
                            }
                            
                    }
                    set<Site_Location_ID__c> allstring =new set<Site_Location_ID__c>();
                      list<string> siteObjList1 =new list<string>();
                     list<string>siteObjList2 =new list<string>();
                     set<string>sitcollectList =new set<string>();
                     List<String> listUnion = new List<String>();
                    if(CustomerSiteList!=null && !CustomerSiteList.isEmpty()){

                            for(Site_Location_ID__c SiteLocationID:[Select Id,Account__c,Customer_SITE_Reference__c , Site_ID__c FROM Site_Location_ID__c where Customer_SITE_Reference__c IN:CustomerSiteList]){      
                                CustomerSiteMap.put(SiteLocationID.Customer_SITE_Reference__c,SiteLocationID.Id);
                                 system.debug('CustomerSiteMap1::' + CustomerSiteMap ); 
                                  siteObjList1.add(SiteLocationID.id);  
                                  system.debug('siteObjList1'+ siteObjList1);
                                 
                               
                            }
                        for(integer j=1;j<filelines.size();j++){
                                system.debug('sit working2');
                                string[] sitObjectvalues1=filelines[j].replaceAll(',(?=[^"]*"[^"]*(?:"[^"]*"[^"]*)*$)','&COMMA').split(',');                        
                                String s = sitObjectvalues1[4].trim(); 
                                
                                if(!CustomerSiteMap.containskey(s)) {                                             
                                        Site_Location_ID__c siteObj = new Site_Location_ID__c();
                                        siteObj.Account__c=Opportunitymap.get(sitObjectvalues1[1].trim());
                                        system.debug('siteObj.Account__c ::' +siteObj.Account__c);
                                        siteObj.Customer_SITE_Reference__c = sitObjectvalues1[4].trim();
                                        siteObj.Region__c = sitObjectvalues1[8];
                                        siteObj.City__c=cityMap.get(sitObjectvalues1[9].trim());
                                        siteObj.ZIP_Code__c=sitObjectvalues1[10];
                                        siteObj.Address_Line_1__c=sitObjectvalues1[11];
                                        siteObj.Address_Line_2__c= sitObjectvalues1[12];
                                        siteObj.Address_Line_3__c= sitObjectvalues1[13];
                                        siteObj.Floor__c = sitObjectvalues1[14];
                                        siteObj.Room__c = sitObjectvalues1[15];
                                        siteObj.Rack__c = sitObjectvalues1[16];  
                                        siteObj.Site_Description__c='Site Creation'; 
                                        siteObj.Site_Status__c='Active';
                                        siteObjList.add(siteObj);
                                        system.debug('siteObjList::' + siteObjList);
                                         
                                        }
                                     
                                    }            
                          
                         if(siteObjList!=null && !siteObjList.isEmpty()){
                                saveResult = database.insert(siteObjList,true); 
                            }
                                for(Database.SaveResult srObj:saveResult){   
                                        if (srObj.isSuccess()){
                                            fReqIdList.add(srObj.getId());
                                            system.debug('fReqIdList ::' +fReqIdList);
                                        }
                                    else{
                                        for(Database.Error err : srObj.getErrors()){
                                            //successFlag =true;
                                             If(!srObj.isSuccess()){
                                             fReqIdListerror.add(srObj.getId());
                                        
                                            }
                                            System.debug('The following error has occurred.');                    
                                            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'  '+err.getMessage()+''+ err.getFields());
                                            ApexPages.addMessage(errormsg);
                                            return null;                        
                                        }
                                    }
                             }                                    
                        siteObjListresult =[Select Id,Customer_SITE_Reference__c ,ZIP_Code__c,Region__c,City__c,Account__c,Site_Description__c,Site_ID__c FROM Site_Location_ID__c WHERE ID IN:fReqIdList];
                            for(Integer i=0; i<siteObjListresult.size(); i++) {
                                    siteObjList2.add(siteObjListresult.get(i).Id);
                                    system.debug('siteObjList2'+siteObjList2); 
                            } 
                    Set<String> setUnion = new Set<String>();
                    setUnion.addAll(siteObjList1);
                    system.debug('siteObjList1' +siteObjList1);
                    setUnion.addAll(siteObjList2);
                    system.debug('siteObjList2' +siteObjList2);
                    listUnion.addAll(setUnion);
                    system.debug('listUnion' +listUnion);
                    }
                
                 if(networkSolCktList!=null && !networkSolCktList.isEmpty()){

                        for(Network_Solution_Circuit__c NetworkSolutionCircuit:[Select Id,Name from Network_Solution_Circuit__c where Name IN:networkSolCktList])
                        {      
                            networkSolCktMap.put(NetworkSolutionCircuit.Name,NetworkSolutionCircuit.Id);       
                            System.debug('networkSolCktMap::'  + networkSolCktMap);
                        }
                    }
                
                    For (Integer i=1;i<filelines.size();i++){ 
                        system.debug('pkp3 filelines :::: '+filelines.size())  ;
                                String[] valuesToInsert = new String[]{};
                                valuesToInsert = filelines[i].split(',');
                                Case feasibilityReq = new Case();
                                feasibilityReq.Products_Services__c = opptyIdProdTypeMap.get((valuesToInsert[1].trim()+'_'+valuesToInsert[2].trim()));                
                                system.debug('Inside Request'+opptyIdProdTypeMap.get((valuesToInsert[1].trim()+'_'+valuesToInsert[2].trim())));
                                feasibilityReq.Ckt_ServiceID__c = valuesToInsert[3];
                                feasibilityReq.Site_Location_ID_A_End__c =listUnion[0]; 
                                system.debug('feasibilityReq site' + feasibilityReq.Site_Location_ID_A_End__c);
                                feasibilityReq.Network_Solution_Circuit_ID__c = networkSolCktMap.get(valuesToInsert[5].trim());
                                system.debug('Network_Solution_Circuit_ID__c:: ' +feasibilityReq.Network_Solution_Circuit_ID__c );
                                                                                              
                                Labelvalue=System.Label.BundleFeasibilitycase.trim();
                                list<string>sheetValuelist =new list<string>();
                                   String sheetValues = valuesToInsert[2].trim();
                                   sheetValuelist.add(sheetValues);
                                     for(string s:sheetValuelist){
                                        if(Labelvalue.contains(s)){
                                               /* A-End Details */ 
                                    feasibilityReq.Continent_A_End__c = valuesToInsert[6];
                                    feasibilityReq.Country_A_End__c = valuesToInsert[7];
                                    feasibilityReq.State_A_End__c = valuesToInsert[8].trim();
                                    feasibilityReq.CityAEnd__c= cityMap.get(valuesToInsert[9].trim());
                                    //feasibilityReq.CityAEnd__c= cityMap.get((valuesToInsert[8].trim()+'_'+valuesToInsert[9].trim()));
                                    feasibilityReq.Pin_Zip_A_End__c = valuesToInsert[10];
                                    feasibilityReq.ADDRESS_LINE1_A_End__c = valuesToInsert[11];
                                    feasibilityReq.ADDRESS_LINE2_A_End__c = valuesToInsert[12];
                                    feasibilityReq.ADDRESS_LINE3_A_End__c = valuesToInsert[13];
                                    feasibilityReq.Floor__c = valuesToInsert[14];
                                    feasibilityReq.Room__c = valuesToInsert[15];
                                    feasibilityReq.Rack__c = valuesToInsert[16];                                    
                                    /* B-End Details */ 
                                    feasibilityReq.Continent_B_End__c = valuesToInsert[17];
                                    feasibilityReq.Country_B_End__c = valuesToInsert[18];
                                    feasibilityReq.State_B_End__c = valuesToInsert[19];
                                    //feasibilityReq.CityBEnd__c= cityMap.get((valuesToInsert[19].trim()+'_'+valuesToInsert[20].trim()));
                                    feasibilityReq.CityBEnd__c= cityMap.get(valuesToInsert[20].trim());
                                    feasibilityReq.Pin_Zip_B_End__c= valuesToInsert[21];
                                    feasibilityReq.ADDRESS_LINE1_B_End__c = valuesToInsert[22];
                                    feasibilityReq.ADDRESS_LINE2_B_End__c = valuesToInsert[23];
                                    feasibilityReq.ADDRESS_LINE3_B_End__c = valuesToInsert[24];
                                    feasibilityReq.Floor_B_End__c = valuesToInsert[25];
                                    feasibilityReq.Room_B_End__c = valuesToInsert[26];
                                    feasibilityReq.Rack_B_End__c = valuesToInsert[27];
                                  
                                    system.debug('working fine');
                                                                                            
                                   }
                                   else{
                                   
                                        /* A-End Details */
                                        feasibilityReq.Continent_A_End__c = valuesToInsert[6];
                                        feasibilityReq.Country_A_End__c = valuesToInsert[7];
                                        feasibilityReq.State_A_End__c = valuesToInsert[8].trim();
                                        //feasibilityReq.CityAEnd__c= cityMap.get((valuesToInsert[8].trim()+'_'+valuesToInsert[9].trim()));
                                        feasibilityReq.CityAEnd__c= cityMap.get(valuesToInsert[9].trim());
                                        feasibilityReq.Pin_Zip_A_End__c = valuesToInsert[10];
                                        feasibilityReq.ADDRESS_LINE1_A_End__c = valuesToInsert[11];
                                        feasibilityReq.ADDRESS_LINE2_A_End__c = valuesToInsert[12];
                                        feasibilityReq.ADDRESS_LINE3_A_End__c = valuesToInsert[13];
                                        feasibilityReq.Floor__c = valuesToInsert[14];
                                        feasibilityReq.Room__c = valuesToInsert[15];
                                        feasibilityReq.Rack__c = valuesToInsert[16];
                                        system.debug('not working fine');
                                          
                                         }
                                       
                                  }                                      
                            
                        Bundle_Feasibility_values__c BFVcase = Bundle_Feasibility_values__c.getInstance('Bundle Values');                        
                            feasibilityReq.Recordtypeid=BFVcase.CaseRecordtype__c;
                            feasibilityReq.Interface__c=BFVcase.Interface__c;
                            feasibilityReq.Status=BFVcase.Status__c;
                            feasibilityReq.Port_Circuit_Capacity__c=BFVcase.Port_Circuit_Capacity__c;
                            feasibilityReq.Last_Mile_Contract_Term__c=BFVcase.Last_Mile_Contract_Term__c;
                            feasibilityReq.Other_POP_A_End__c=BFVcase.Other_POP_A_End__c;
                            feasibilityReq.SPECIAL_REQUIREMENTS__c=BFVcase.SPECIAL_REQUIREMENTS__c;
                            feasibilityReq.Available_Telecom_PRI_Provider_A_End__c=BFVcase.Available_Telecom_PRI_Provider_A_End__c;
                            feasibilityReq.Other_POP_B_End__c=BFVcase.Other_POP_B_End__c;
                            feasibilityReq.Available_Telecom_PRI_Provider_B_End__c=BFVcase.Available_Telecom_PRI_Provider_B_End__c;                              
                            feasibilityReq.Request_Type__c=BFVcase.Request_Type__c;
                            caseList.add(feasibilityReq);
                        }               
                
                 if(caseList!=null && !caseList.isEmpty()){
                        saveResult = database.insert(caseList,False); 
                    }
                if(saveResult != null && !saveResult.isEmpty()){
                        //successcaseList = new list<case>();

                            for(Database.SaveResult srObj:saveResult){   
                                    if (srObj.isSuccess()){fReqIdList.add(srObj.getId());}
                                else{
                                    for(Database.Error err : srObj.getErrors()){
                                            If(!srObj.isSuccess()){fReqIdListerror.add(srObj.getId());}
                                            
                                        System.debug('The following error has occurred.');                    
                                        ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'  '+err.getMessage()+''+ err.getFields());
                                        ApexPages.addMessage(errormsg);
                                        return null;                        
                                    }
                                }
                            }
                      
                    successcaseList = [SELECT id,Products_Services__c,Ckt_ServiceID__c, Status,Port_Circuit_Capacity__c,Continent_A_End__c,Country_A_End__c,State_A_End__c,CityAEnd__c,ADDRESS_LINE1_A_End__c,ADDRESS_LINE2_A_End__c,ADDRESS_LINE3_A_End__c,Pin_Zip_A_End__c,Available_Telecom_PRI_Provider_A_End__c,Floor__c FROM Case WHERE ID IN  :fReqIdList];
                      system.debug('successcaseList2' + successcaseList );
                       //Id ResponseId = Schema.SObjectType.Feasibility_Response_A__c.getRecordTypeInfosByName().get('Wireline - MAN/VBL').getRecordTypeId();
                               if(successcaseList != null && !successcaseList.isEmpty()){
                                             successFlag = true;
                                                system.debug('successfully insert');
                                            List<Feasibility_Task__c> FeasibilityTasklist= new list<Feasibility_Task__c>();
                                            
                                    for(integer i=0;i<successcaseList.size();i++)
                                    {
                                     Bundle_Feasibility_values__c BFVTask = Bundle_Feasibility_values__c.getInstance('Bundle Values'); 
                                        Feasibility_Task__c FeasibilityTask =new Feasibility_Task__c();
                                        FeasibilityTask.Feasibility_Request__c=successcaseList[i].id;
                                        FeasibilityTask.Subject__c =BFVTask.Subject__c;
                                        FeasibilityTask.Status__c =BFVTask.Status__c;
                                        FeasibilityTask.Overall_Feasibility_Status__c =BFVTask.Overall_Feasibility_Status__c;
                                        FeasibilityTask.Group_Working_on_the_Task__c =BFVTask.Group_Working_on_the_Task__c;
                                        FeasibilityTask.Task_Close_Date__c=system.today();
                                        FeasibilityTask.Sub_Group__c=BFVTask.SubGroup__c ;
                                        FeasibilityTask.Task_Acknowledged_By__c='Abdul Munaf Sheikh';
                                        FeasibilityTasklist.add(FeasibilityTask);
                                    
                                    }
                                        if(FeasibilityTasklist!=null &&!FeasibilityTasklist.isEmpty())
                                        {
                                            saveResult = database.insert(FeasibilityTasklist,true); 
                                            
                                        }
                                        if(saveResult != null && !saveResult.isEmpty()){
                                                for(Database.SaveResult srObj1:saveResult)
                                                {
                                                    if (srObj1.isSuccess()) {
                                                        FeasibilityTaskId.add(srObj1.getId()); 
                                                        System.debug('FeasibilityTaskId::'+ FeasibilityTaskId);           
                                                        
                                                    }else{
                                                        for(Database.Error err1 : srObj1.getErrors())
                                                        {                
                                                                                
                                                            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'  '+err1.getMessage()+''+ err1.getFields());
                                                            ApexPages.addMessage(errormsg);
                                                            return null;
                                                            
                                                        }                                    
                                                        
                                                    }
                                                }
                                            
                                        }
                          FeasibilityTasklist1 =[Select Id,Name,CreatedDate,Feasibility_Request__r.Port_Feasibility_Flag__c,Feasibility_Request__r.Other_POP_A_End__c,Feasibility_Request__r.City_A_End__c,Feasibility_Request__r.State_A_End__c,Feasibility_Request__r.Country_A_End__c,Feasibility_Request__r.Port_Circuit_Capacity__c,Feasibility_Request__r.Products_Services__r.Cloud_Provider__c from Feasibility_Task__c where Feasibility_Request__c IN:successcaseList];
                                     system.debug('FeasibilityTasklist1 ::' +FeasibilityTasklist1);
                                     iF(FeasibilityTasklist1 !=null && !FeasibilityTasklist1.isEmpty()){
                                           
                                           for(integer i=0;i<FeasibilityTasklist1.size();i++)
                                            {           
            Bundle_Feasibility_values__c BFVResponse = Bundle_Feasibility_values__c.getInstance('Bundle Values');                                            
                      Feasibility_Response_A__c FeasibilityResponse = new Feasibility_Response_A__c(); 
                                                FeasibilityResponse.Recordtypeid=BFVResponse.Responserecordtype__c;
                                                FeasibilityResponse.Feasibility_Task__c = FeasibilityTasklist1[i].Id;
                                                FeasibilityResponse.Case__c = successcaseList[i].id;
                                                FeasibilityResponse.Response_Related_To__c  =BFVResponse.Response_Related_To__c;
                                                FeasibilityResponse.Feasibility_Status__c =BFVResponse.Feasibility_Status__c;
                                                FeasibilityResponse.Provider_Name__c=BFVResponse.Provider_Name__c;
                                                FeasibilityResponse.LM_Contract_Term__c=BFVResponse.LM_Contract_Term__c;
                                                FeasibilityResponse.Provider_Request_Date__c=System.today();
                                                FeasibilityResponse.Provider__c=System.today();
                                                FeasibilityResponse.Feasiblity_Expiry_Date__c=Date.today().addDays(30) ;
                                                FeasibilityResponse.Feasibility_Status_Category__c=BFVResponse.Feasibility_Status_Category__c;
                                                FeasibilityResponse.TCL_POP_Address__c=BFVResponse.TCL_POP_Address__c;
                                                FeasibilityResponse.Local_Loop_Interface__c=BFVResponse.Local_Loop_Interface__c;
                                                FeasibilityResponse.Sales_Selected_Response__c=BFVResponse.Sales_Selected_Response__c;
                                                FeasibilityResponse.Local_Loop_Capacity__c=BFVResponse.Local_Loop_Capacity__c;
                                                FeasibilityResponse.POP_Address__c='a6N20000000aJ10';
                                                
                                                FeasibilityResponselist.add(FeasibilityResponse);
                                                
                                            }
                                            
                                        }                                    
                                    if(FeasibilityResponselist!=null && !FeasibilityResponselist.isEmpty()){
                                         saveResult = database.insert(FeasibilityResponselist,true);           
                                        System.debug('saveResult::'+saveResult);
                                        }   
                                        if(saveResult != null && !saveResult.isEmpty()){
                                                for(Database.SaveResult srObj2:saveResult)
                                                {
                                                    if (srObj2.isSuccess()) {
                                                        FeasibilityResponseId.add(srObj2.getId()); 
                                                        System.debug('FeasibilityResponseId::'+FeasibilityResponseId);           
                                                        
                                                    }else{
                                                        for(Database.Error err2 : srObj2.getErrors())
                                                        {                       
                                                            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'  '+err2.getMessage()+''+ err2.getFields());
                                                            ApexPages.addMessage(errormsg);
                                                            return null;
                                                            
                                                        }                                    
                                                        
                                                    }
                                                }
                                            
                                        }
                                        
                                    }                                   
                      //successFullcase();
                       ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'successfully case completed: ');
                       ApexPages.addMessage(errormsg);
                    }
               
                }
               else
               {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Please Upload Only CSV Files.'));
                
                }
            }
          else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Please Select A File To Upload'));
             
            }
       
     
  Return null;
 }
 
      
     public PageReference cancel() {
     pageReference page = new pageReference('/apex/BundleFeasibilitypage');
     page.setRedirect(true);
      return page;
     //return null;
      
    } 
  /*   
  public PageReference successFullcase() {
       if(caseid!=null && !caseid.isEmpty())
       {
           return Page.BundleFeasibilitySuccessResult;
           
       }
       else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'There are no successfully inserted Bundle Feasibilitypage'));
            return null;
        }
      
        
    }
  */ 

public static String blobToString(Blob input, String inCharset){
        String hex = EncodingUtil.convertToHex(input);
        
        System.assertEquals(0, hex.length() & 1);
        final Integer bytesCount = hex.length() >> 1;
        String[] bytes = new String[bytesCount];
        for(Integer i = 0; i < bytesCount; ++i)
        bytes[i] =  hex.mid(i << 1, 2);
    System.Debug('pkppkp '+EncodingUtil.urlDecode('%' + String.join(bytes, '%'), inCharset));  
        return EncodingUtil.urlDecode('%' + String.join(bytes, '%'), inCharset);
    
    }  
}

**Comment by sricharananand** [comment]
unrelated to CMD loader - closing this issue
