### ISSUE TITLE
Attempt to de-reference a null object

### ISSUE THREAD

**Issue by RahimRahimov** [forcedotcom/CustomMetadataLoader#18]
```
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

An unexpected error has occurred. Your development organization has been notified.
```

The same issue when i try to upload the sample.csv file. Could you please explain how to fix this problem?

**Comment by liz-mangano** [comment]
I'm having the exact same issue. Probably going to be faster to manually create the records at this point. Bummer. Disappointing first impression of what could be a really cool tool!

**Comment by keerthanshetty25** [comment]
Hi 
Even i had faced the similar issue using this tool and i feel there is issue with controller coding of the package. but i have done workaround which will work. below are the steps you have to do to upload the content
1. once you create .csv file open this file in notepad++ and and replace comma(,) with semicolon(;) for all
2.Save the file as .csv itself and now upload this file in custom meta data loader.

it has worked for me i hope it will work for you also

Thanks

**Comment by vinita1bisht** [comment]
@keerthanshetty25 that worked! Thank you so much!

**Comment by bla1ne** [comment]
Happened to me as well.
@keerthanshetty25 workaround worked like a charm.

**Comment by ministe2003** [comment]
I personally found that the fix for this was to update MetadataUtil lines 65-72 with this:
```
        Set<String> fieldNameSet **= new Set<String>();**  
        for (String fieldNames :header) {
            if (String.isBlank(fieldNames)) {
                continue;
            }

            fieldNameSet**.addAll(fieldNames.split(';'));**
        }
```
and lines 87-95 with this:
```
            List<String> fieldValueList **= new List<String>();**

            for (String singleRowFieldValues :singleRowOfValues) {
                if (String.isBlank(singleRowFieldValues)) {
                    continue;
                }
            
                fieldValueList**.addAll(singleRowFieldValues.split(';'));**
            }
```

I would submit a pull request for this, but not sure if it's the perfect fix for everyone or not.  I found that since the sets were being assigned each time in the loop rather than just adding to the set, it was overwriting the previous column's data

**Comment by sricharananand** [comment]
Issue should be resolved now via commit on Aug 9, 2017 - closing this issue.
