### ISSUE TITLE
"Attempt to de-reference a null object" - Error Upon Insert of New Custom Metadata

### ISSUE THREAD

**Issue by pankaj90** [forcedotcom/CustomMetadataLoader#25]
I tried using v2.0 with a CSV file, but still I am receiving below error message:

System.NullPointerException: Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component apex:commandButton in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by adhisun** [comment]
I am getting the same error. Installed from Heroku to SF.

Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by adhisun** [comment]
Was able to resolve this after changing the file delimiter as ; instead of ,

fieldNames.split(';')

**Comment by sricharananand** [comment]
Issue should be resolved now via commit on Aug 9, 2017 - closing this issue.

**Comment by sricharananand** [comment]
Issue should be resolved now via commit on Aug 9, 2017 - closing this issue.
