### ISSUE TITLE
Error on line 89 of MetadataUtil.cls - List is missing the 'L' - will not deploy

### ISSUE THREAD

**Issue by kurtfairfield** [forcedotcom/CustomMetadataLoader#26]
![image](https://user-images.githubusercontent.com/18200424/29155075-47915036-7d4e-11e7-9315-bd020e33a5ea.png)
Seems like code is corrupted a bit in MetadataUtil.cls. We lost an 'L' along the way.

**Comment by sricharananand** [comment]
Resolved typo with latest commit - sorry about the typo. Tested app deploy and importing cmd records - works fine.

**Comment by kurtfairfield** [comment]
Thanks for the quick fix. I downloaded the code and was going to fix it and then package it back up and deploy to SF, but I haven't done that before. Is there a way I could have edited the code myself on the GIT hub and submitted it for approval? I am a SF developer so GIT is newish to me...

**Comment by sricharananand** [comment]
@kurtfairfield Yes, you can make the changes in code, and submit for approval - i get a notification, i need to merge your changes(pull) if it looks good. Thanks again for your help and support! Much appreciated.
