### ISSUE TITLE
Error importing sample: "BLOB is not a valid UTF-8 string"

### ISSUE THREAD

**Issue by benderguy** [forcedotcom/CustomMetadataLoader#31]
When I try to upload even the sample CSV I get this error message:
```
Error:
An error has occured while importin data. Please make sure input csv file is correct
BLOB is not a valid UTF-8 string
null
```

How do I resolve this? Perhaps this has something to do with the namespace, which is blank/null on the sample and my custom CMT object?

**Comment by jeff881208** [comment]
You just need to convert the csv from UTF-8-BOM to UTF-8 through notepad++ or other tools.
I think this is a bug .

**Comment by benderguy** [comment]
Thanks. In my case one value had a apostrophe in the text. That's a valid character in CMTs, but getting rid of it for the purposes of importing seemed to fix that issue.
