### ISSUE TITLE
Cannot create a new component with the namespace: myNameSpace. Only components in the same namespace as the organization can be created through the API

### ISSUE THREAD

**Issue by choovick** [forcedotcom/CustomMetadataLoader#4]
Hello, installed this app via deploy button into my sandbox, now getting this when attempting to create Remote Site Setting via button on the app:
**Cannot create a new component with the namespace: myNameSpace. Only components in the same namespace as the organization can be created through the API**

Can we get instructions on how this can be created manually? or I have to reverse engineer VF page? :)

**Comment by choovick** [comment]
Found a solution: http://www.srinivas4sfdc.com/2016/01/setting-and-uploading-custom-metadata.html

Closing.

**Comment by michacom** [comment]
Also, use the tool in Classic Experience **ONLY**
