### ISSUE TITLE
"Attempt to de-reference a null object" error in CustomMetadataUploadControllerTest

### ISSUE THREAD

**Issue by Bard09** [forcedotcom/CustomMetadataLoader#5]
Hi there,

We deployed this today on our Sandbox and this worked great, but when we tried to deploy it to our Production instance we noticed that the CustomMetadataUploadControllerTest was failing.  Here's the error log.

> **Class**	
> CustomMetadataUploadControllerTest
> **Method Name**	
> testCreateCustomMetadataWithDevName
> **Error Message**
> System.NullPointerException: Attempt to de-reference a null object
> **Stack Trace**	
> Class.MetadataService.MetadataPort.upsertMetadata: line 9274, column 1
> Class.MetadataUtil.upsertMetadataAndValidate: line 131, column 1
> Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 97, column 1
> Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 127, column 1
> Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
> Class.CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName: line 54, column 1

> **Class**	
> CustomMetadataUploadControllerTest
> **Method Name**	
> testCreateCustomMetadata
> **Error Message**	
> System.NullPointerException: Attempt to de-reference a null object
> **Stack Trace**	
> Class.MetadataService.MetadataPort.upsertMetadata: line 9274, column 1
> Class.MetadataUtil.upsertMetadataAndValidate: line 131, column 1
> Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 97, column 1
> Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 127, column 1
> Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
> Class.CustomMetadataUploadControllerTest.testCreateCustomMetadata: line 44, column 1

Any ideas what's causing this?  It's hard to tell when deploying external code if it's a problem on your end or ours.  

We added a Remote Site Setting in advance of the Production deployment in the event that was the cause, but it doesn't seem to have addressed the issue.

**Comment by sricharananand** [comment]
We will take a look at the test. Irrespective of the test, you should still be able to use the tool and deploy to your Production instance.

**Comment by Bard09** [comment]
Thank you for taking a look!  

I don't believe that to be the case (deploying to Production despite this error).  When using the Deploy tool (https://githubsfdeploy.herokuapp.com) to our Production environment, I got the following error displayed.  This didn't happen on our Sandboxes as those aren't executing test code by default during deployments.

Let me know if you need any other information.  Happy to be a guinea pig to help you resolve!

> Status: InProgress 
> Status: Completed 
> Deployment CompleteTest failure, method: CustomMetadataUploadControllerTest.testCreateCustomMetadata -- System.NullPointerException: Attempt to de-reference a null object stack Class.MetadataService.MetadataPort.upsertMetadata: line 9274, column 1
> Class.MetadataUtil.upsertMetadataAndValidate: line 131, column 1
> Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 97, column 1
> Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 127, column 1
> Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
> Class.CustomMetadataUploadControllerTest.testCreateCustomMetadata: line 44, column 1
> 
> Test failure, method: CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName -- System.NullPointerException: Attempt to de-reference a null object stack Class.MetadataService.MetadataPort.upsertMetadata: line 9274, column 1
> Class.MetadataUtil.upsertMetadataAndValidate: line 131, column 1
> Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 97, column 1
> Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 127, column 1
> Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
> Class.CustomMetadataUploadControllerTest.testCreateCustomMetadataWithDevName: line 54, column 1

**Comment by goravseth** [comment]
Same error as above.  

I tested deploying via the deploy to salesforce button as well as via workbench.

If I set to run local tests I get the same error as above.

If i specify a single local test to run that is not part of this repo, I get code coverage error.

I suppose I could deploy to sandbox and then move to prod via change set, excluding the tests that are causing errors, but would be great if this could be resolved.

**Comment by FishOfPrey** [comment]
As per [Null pointer Exception in test classes when installing the Custom Metadata Loader](http://salesforce.stackexchange.com/q/151516/102), the problem is in MDWrapperWebServiceMock. It needs to return a `MetadataService.upsertMetadataResponse_element`.

I'll see if I can create a pull request to fix this.

**Comment by aroyfaderman** [comment]
Thanks, @FishOfPrey !

**Comment by nickanderson86** [comment]
Hi, all! I'm running in to this error, too. Looks like there's a patch above, but I'm a bit of a noob and I'm not sure how I go about adding this to the SFDC org. Can you please provide some instructions? Thanks!

**Comment by shishpalchauhan288** [comment]
This Kind of Error is shown when I am Inserting the records using  custom metadata type loader 
Kindly Assist me.

Error: An error has occurred while saving dataAttempt to de-reference a null object---116
