### ISSUE TITLE
Cannot create a new component with the namespace: My domain. Only components in the same namespace as the organization can be created through the API

### ISSUE THREAD

**Issue by AFenoys** [forcedotcom/CustomMetadataLoader#55]
After activate my domain i cannot use custom metada loader. I have the next Issue:

I tried the solution given here: http://www.srinivas4sfdc.com/2016/01/setting-and-uploading-custom-metadata.html
And still not working.
Any solution?
Thanks

**Comment by AFenoys** [comment]
After a lot of tries, the solution was copy paste **the page of error in classic** , and put it, in the **remote site settings**

**Comment by DeepikaMatam** [comment]
Step by step instruction & Fix details are below
https://deepikamatam.blogspot.com/2019/11/custom-metadata-loader.html
