### ISSUE TITLE
Remote Site Settings Issue

### ISSUE THREAD

**Issue by brittaneybt** [forcedotcom/CustomMetadataLoader#83]
I installed this package by clicking deploy to Salesforce and I'm struggling to create a remote site setting for Lightning. 

![image](https://user-images.githubusercontent.com/52251835/124034945-7cc2f880-d9c1-11eb-871b-63c73e762e9a.png)
![image](https://user-images.githubusercontent.com/52251835/124034978-83ea0680-d9c1-11eb-8c9e-1c86d8d4c24d.png)

I attempted to troubleshoot with https://www.srinivas4sfdc.com/2016/01/setting-and-uploading-custom-metadata.html
but I'm not having any luck.
Could someone please help?

**Comment by bigl900** [comment]
1. Go to setup and search for Visualforce pages
2. Find the page Called: "CustomMetadataLoader"
3. Either click on the preview icon or open the page and click preview
4. The CustomMetadataLoader page will come up
5. Copy that URL
6. Replace the Remote Site URL in your screenshot with the copied URL

**Comment by brittaneybt** [comment]
Hi @bigl900, we're making progress. A new error message appears. Do you have any idea how to overcome this? I tried reaching out to Salesforce support, but they refused to help. 

Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=
Error is in expression '{!checkMdApi}' in component <apex:page> in page custommetadataloader: Class.MetadataService.MetadataPort.listMetadata: line 9218, column 1
Class.MetadataUtil.checkMetadataAPIConnection: line 30, column 1
Class.CustomMetadataLoaderController.checkMdApi: line 16, column 1

An unexpected error has occurred. Your development organization has been notified.

![image](https://user-images.githubusercontent.com/52251835/124654653-6eaf2500-de64-11eb-8ae4-2d3c0ed2b221.png)


I received an email notification about the error:
Apex script unhandled exception by user/organization: 0053s000002ttfJ/00D6A000002GtQ5

Visualforce Page: /apex/CustomMetadataLoader

caused by: System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

Class.MetadataService.MetadataPort.listMetadata: line 9218, column 1
Class.MetadataUtil.checkMetadataAPIConnection: line 30, column 1
Class.CustomMetadataLoaderController.checkMdApi: line 16, column 1

**Comment by bigl900** [comment]
Can you check 'Lock sessions to the IP address from which they originated.' setting under Session Settings under Setup? I found another article stating that that might need to be disabled for this to work.

**Comment by brittaneybt** [comment]
I wish that worked. I still have the same error @BhanuTabeti 

Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=
Error is in expression '{!checkMdApi}' in component <apex:page> in page custommetadataloader: Class.MetadataService.MetadataPort.listMetadata: line 9218, column 1
Class.MetadataUtil.checkMetadataAPIConnection: line 30, column 1

![image](https://user-images.githubusercontent.com/52251835/124669105-762bf980-de77-11eb-9c47-7af20b594220.png)

Class.CustomMetadataLoaderController.checkMdApi: line 16, column 1

An unexpected error has occurred. Your development organization has been notified.

**Comment by bigl900** [comment]
Found another article with the error that pointed at this update that Salesfroce made to metadata access

https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_forcecom_development_custom_metadata_require_cruc.htm

To grant a profile or permission set read access to a custom metadata type:

1. Go to the profile or permission set that you want to grant access to.
2. Under Enabled Custom Metadata Type Access, click Edit.
3. Add the custom metadata type to the list of enabled custom metadata types.

To re-enable read access to custom metadata outside of Apex code or system mode contexts:

1. In Setup, navigate to Schema Settings.
2. Deselect Restrict access to custom metadata.

**Comment by brittaneybt** [comment]
Hi @bigl900, I have no idea what changed in the org (maybe a NPSP update), but I was able to get the custom metadata loader working. Thank you so much for all your help troubleshooting!
